### ISSUE TITLE
Working function to calculate slope intercept

### ISSUE THREAD

**Issue by samanthaduke** [Samantha-Eaton-Duke/547#18]
https://github.com/Samantha-Eaton-Duke/547/blob/104184298a5aa918f124624956beeb3480f12828/line.py

**Comment by dward2** [comment]
Your calculation functions look good.  There is only one issue I see.  When we want to test a function, it needs to be able to receive inputs from a test function and it needs to return an output back to the test function so that the test function can check to see if it did the calculations correctly.

In your `line_point` function:
https://github.com/Samantha-Eaton-Duke/547/blob/104184298a5aa918f124624956beeb3480f12828/line.py#L33-L38
Ask yourself:
1. Does this function accept inputs?
2. Does this function return an answer?

**Comment by samanthaduke** [comment]
I thought that it did accept inputs, do I need to have the inline function say input()?

**Comment by dward2** [comment]
> I thought that it did accept inputs, do I need to have the inline function say input()?

Yes, your function does have input (the parameters are what I mean by input in this situation.  What it does not currently have is a "return."  You only print to the screen.  So, you need to `return y` so your test_function will have something to test.
